CREATE DATABASE BIBLIOTECA
GO
USE BIBLIOTECA

GO

CREATE TABLE EDITORIAL(
	ID INT PRIMARY KEY,
	NOMBRE VARCHAR(50),
)

CREATE TABLE LIBRO(
	ISBN VARCHAR(50) PRIMARY KEY,
	AUTOR VARCHAR(50),
	NOMBRE VARCHAR(50),
	EXISTENCIA INT,
	CONSULTA BIT,
	EDITORIAL INT FOREIGN KEY REFERENCES EDITORIAL(ID)
)

CREATE TABLE PRESTAMO(
	CLAVE INT IDENTITY(1,1) PRIMARY KEY,
	ISBN VARCHAR(50) FOREIGN KEY REFERENCES LIBRO(ISBN),
	USUARIO VARCHAR(50),
	TIPOUSUARIO VARCHAR(50),
)

GO

INSERT INTO EDITORIAL(ID,NOMBRE)
VALUES (1,'LUNAS'),
(2,'GALLEGOS'),
(3,'PALACIOS')

SELECT ID FROM EDITORIAL WHERE NOMBRE = 'PALACIOS'

INSERT INTO LIBRO(ISBN,AUTOR,NOMBRE,EXISTENCIA,CONSULTA,EDITORIAL)
VALUES('9325OUIEIFASR','FERNANDO','PROGRAMACION II',5,0,2)

SELECT * FROM LIBRO

SELECT L.ISBN,L.AUTOR,L.NOMBRE,L.EXISTENCIA,L.CONSULTA,E.NOMBRE FROM LIBRO L INNER JOIN EDITORIAL E
ON L.EDITORIAL = E.ID

